### ISSUE TITLE
Support unconnected nodes #32 pull request is not passing Julia Nightly

### ISSUE THREAD

**Issue by maikkirapo** [JuliaFEM/NodeNumbering.jl#33]
Support unconnected nodes #32 pull request is not passing Julia Nightly and I can't find out why.

Error only says: 
The command "julia --color=yes -e 'using PkgTestSuite; init()'" failed and exited with 1 during .

**Comment by ahojukka5** [comment]
That is all Travis-CI is outputting to log?
